"""Initial corpus schema: sources, documents, chunks, runs, skips.

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-25

Hand-written rather than autogenerated. Three things here cannot be expressed
through SQLAlchemy's DDL and are the whole reason this migration matters:
the pgvector extension and HNSW index (ADR-0004), the tsvector trigger that
keeps lexical search honest, and the index build parameters.
"""

from __future__ import annotations

import os

import sqlalchemy as sa
from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

# ADR-0002. Read from the environment so a deployment that has chosen a
# different provider builds the right column width from the start; the boot-time
# check in the application then compares this against the live provider.
DIMENSIONS = int(os.environ.get("RAGOOGLE_EMBEDDING_DIMENSIONS", "1024"))


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # pg_trgm backs fuzzy title matching in the config UI's document search. It
    # is unrelated to retrieval and deliberately not part of ADR-0004's pipeline.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.create_table(
        "sources",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("provider", sa.String(64), nullable=False),
        sa.Column("auth_mode", sa.String(32), nullable=False),
        sa.Column("credential_ref", sa.Text, nullable=False),
        sa.Column("principal", sa.Text, nullable=False),
        sa.Column("enabled", sa.Boolean, nullable=False, server_default="true"),
        sa.Column(
            "root_folder_ids",
            sa.dialects.postgresql.ARRAY(sa.Text),
            nullable=False,
            server_default="{}",
        ),
        sa.Column(
            "include_mime_types",
            sa.dialects.postgresql.ARRAY(sa.Text),
            nullable=False,
            server_default="{}",
        ),
        sa.Column(
            "exclude_mime_types",
            sa.dialects.postgresql.ARRAY(sa.Text),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("max_document_bytes", sa.BigInteger, nullable=True),
        sa.Column(
            "metadata_json", sa.dialects.postgresql.JSONB, nullable=False, server_default="{}"
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.CheckConstraint("auth_mode IN ('service_account', 'oauth')", name="auth_mode_is_known"),
        sa.CheckConstraint(
            "max_document_bytes IS NULL OR max_document_bytes > 0",
            name="max_document_bytes_positive",
        ),
        sa.UniqueConstraint("provider", "name", name="uq_sources_provider_name"),
    )

    op.create_table(
        "documents",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "source_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("sources.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("external_id", sa.Text, nullable=False),
        sa.Column("title", sa.Text, nullable=False),
        sa.Column("mime_type", sa.String(255), nullable=False),
        sa.Column("web_url", sa.Text, nullable=True),
        sa.Column(
            "folder_path",
            sa.dialects.postgresql.ARRAY(sa.Text),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checksum", sa.String(128), nullable=True),
        sa.Column("size_bytes", sa.BigInteger, nullable=True),
        sa.Column(
            "metadata_json", sa.dialects.postgresql.JSONB, nullable=False, server_default="{}"
        ),
        sa.Column(
            "ingested_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.UniqueConstraint("source_id", "external_id", name="uq_documents_source_id_external_id"),
    )
    op.create_index("ix_documents_source_id", "documents", ["source_id"])
    op.create_index("ix_documents_modified_at", "documents", ["modified_at"])
    op.execute("CREATE INDEX ix_documents_title_trgm ON documents USING gin (title gin_trgm_ops)")

    op.create_table(
        "chunks",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "document_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("documents.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("ordinal", sa.Integer, nullable=False),
        sa.Column("text", sa.Text, nullable=False),
        sa.Column("token_count", sa.Integer, nullable=False),
        sa.Column(
            "heading_path",
            sa.dialects.postgresql.ARRAY(sa.Text),
            nullable=False,
            server_default="{}",
        ),
        sa.Column(
            "metadata_json", sa.dialects.postgresql.JSONB, nullable=False, server_default="{}"
        ),
        sa.Column("search_vector", sa.dialects.postgresql.TSVECTOR, nullable=True),
        sa.Column("embedding_model", sa.String(128), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.CheckConstraint("ordinal >= 0", name="ordinal_non_negative"),
        sa.CheckConstraint("token_count > 0", name="token_count_positive"),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_chunks_document_id_ordinal"),
    )
    op.execute(f"ALTER TABLE chunks ADD COLUMN embedding vector({DIMENSIONS})")
    op.create_index("ix_chunks_document_id", "chunks", ["document_id"])

    # -- ADR-0004, half one: dense recall -------------------------------
    #
    # HNSW over IVFFlat: IVFFlat needs representative data present before the
    # index is built to cluster sensibly, which an empty corpus cannot provide,
    # and its recall degrades as the corpus drifts away from those clusters.
    # HNSW builds incrementally and holds recall as rows arrive.
    #
    # Cosine (`vector_cosine_ops`) because voyage-3-large embeddings are
    # normalised, making cosine and inner product rank-equivalent -- cosine is
    # the one that stays correct if a future provider does not normalise.
    op.execute(
        "CREATE INDEX ix_chunks_embedding_hnsw ON chunks "
        "USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )

    # -- ADR-0004, half two: lexical recall -----------------------------
    #
    # The trigger, rather than application-side population, is the point. A
    # chunk inserted by a backfill or by psql becomes searchable on identical
    # terms to one written by the ingester. Lexical recall that depends on
    # remembering to set a column is lexical recall that rots silently, and the
    # symptom -- exact-match queries quietly failing -- is the precise failure
    # hybrid retrieval exists to prevent.
    #
    # Heading path is weighted 'A' and body 'B': a query matching a section
    # title is a stronger signal than the same term buried in prose.
    op.execute(
        """
        CREATE FUNCTION chunks_search_vector_update() RETURNS trigger AS $$
        BEGIN
            NEW.search_vector :=
                setweight(to_tsvector('english',
                    coalesce(array_to_string(NEW.heading_path, ' '), '')), 'A') ||
                setweight(to_tsvector('english', coalesce(NEW.text, '')), 'B');
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER chunks_search_vector_trigger "
        "BEFORE INSERT OR UPDATE OF text, heading_path ON chunks "
        "FOR EACH ROW EXECUTE FUNCTION chunks_search_vector_update()"
    )
    op.execute("CREATE INDEX ix_chunks_search_vector ON chunks USING gin (search_vector)")

    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "source_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("sources.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("state", sa.String(32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cursor", sa.Text, nullable=True),
        sa.Column("discovered", sa.Integer, nullable=False, server_default="0"),
        sa.Column("ingested", sa.Integer, nullable=False, server_default="0"),
        sa.Column("unchanged", sa.Integer, nullable=False, server_default="0"),
        sa.Column("skipped", sa.Integer, nullable=False, server_default="0"),
        sa.Column("failed", sa.Integer, nullable=False, server_default="0"),
        sa.Column("error", sa.Text, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'running', 'completed', 'failed', 'cancelled')",
            name="state_is_known",
        ),
        sa.CheckConstraint(
            "state NOT IN ('completed', 'failed', 'cancelled') OR finished_at IS NOT NULL",
            name="terminal_runs_have_finished_at",
        ),
        sa.CheckConstraint("state <> 'failed' OR error IS NOT NULL", name="failed_runs_record_why"),
    )
    op.execute(
        "CREATE INDEX ix_ingestion_runs_source_id_created_at "
        "ON ingestion_runs (source_id, created_at DESC)"
    )

    op.create_table(
        "skip_records",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column(
            "run_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("ingestion_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("external_id", sa.Text, nullable=False),
        sa.Column("reason", sa.String(64), nullable=False),
        sa.Column("principal", sa.Text, nullable=False),
        sa.Column("title", sa.Text, nullable=True),
        sa.Column(
            "folder_path",
            sa.dialects.postgresql.ARRAY(sa.Text),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("detail", sa.Text, nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "reason IN ('permission_denied', 'unsupported_type', 'too_large', "
            "'extraction_failed', 'trashed', 'empty')",
            name="reason_is_known",
        ),
    )
    op.create_index("ix_skip_records_run_id", "skip_records", ["run_id"])
    op.create_index("ix_skip_records_reason", "skip_records", ["reason"])


def downgrade() -> None:
    op.drop_table("skip_records")
    op.drop_table("ingestion_runs")
    op.execute("DROP TRIGGER IF EXISTS chunks_search_vector_trigger ON chunks")
    op.execute("DROP FUNCTION IF EXISTS chunks_search_vector_update()")
    op.drop_table("chunks")
    op.drop_table("documents")
    op.drop_table("sources")
    # Extensions are deliberately left in place: they may be shared with other
    # schemas in the same database, and dropping one is not this migration's to
    # decide.
